"""empty message

Revision ID: 05eb9a50ddec
Revises: 6053b5ce7cdc
Create Date: 2026-06-10 13:03:40.311753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eb9a50ddec'
down_revision = '6053b5ce7cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('org_type')

    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.alter_column('fault_detected_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.alter_column('fault_detected_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
