"""empty message

Revision ID: 0cd9ce0e6e70
Revises: aa9d32443a19
Create Date: 2026-07-03 19:18:57.503186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd9ce0e6e70'
down_revision = 'aa9d32443a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('org_type', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('org_type')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
