"""add deletion mark

Revision ID: 1901cef5ccfa
Revises: 577cef9e43b0
Create Date: 2026-03-31 19:20:15.793082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1901cef5ccfa'
down_revision = '577cef9e43b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Technical Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletion_mark', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Technical Task', schema=None) as batch_op:
        batch_op.drop_column('deletion_mark')

    # ### end Alembic commands ###
