"""empty message

Revision ID: 49554bbaae23
Revises: d6d0f5ec582d
Create Date: 2026-09-01 11:40:19.700087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49554bbaae23'
down_revision = 'd6d0f5ec582d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_person', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_ref', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.drop_column('doc_ref')

    with op.batch_alter_table('task_person', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
