"""empty message

Revision ID: 5501b4e6e676
Revises: 7c46ea2e47ab
Create Date: 2026-06-22 12:09:47.104634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5501b4e6e676'
down_revision = '7c46ea2e47ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person_info.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['technical_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('technical_task_person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_task_person',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person_info.id'], name=op.f('technical_task_person_person_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['technical_task.id'], name=op.f('technical_task_person_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('technical_task_person_pkey'))
    )
    op.drop_table('task_person')
    # ### end Alembic commands ###
