"""add title

Revision ID: 577cef9e43b0
Revises: f5302bb9363a
Create Date: 2026-03-16 17:48:56.314166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577cef9e43b0'
down_revision = 'f5302bb9363a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Technical Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Technical Task', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
