"""add deleting author to technical task

Revision ID: 6053b5ce7cdc
Revises: 678b9ae89d70
Create Date: 2026-06-05 17:51:38.223187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6053b5ce7cdc'
down_revision = '678b9ae89d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleting_author_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'person_info', ['deleting_author_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('technical_task_person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('technical_task_person_person_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'person_info', ['person_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task_person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('technical_task_person_person_id_fkey'), 'person_info', ['person_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleting_author_id')

    # ### end Alembic commands ###
