"""empty message

Revision ID: 669e6293bbf5
Revises: cfa572c2edab
Create Date: 2026-04-21 17:44:14.431840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669e6293bbf5'
down_revision = 'cfa572c2edab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
