"""empty message

Revision ID: 78508fc70a67
Revises: 1901cef5ccfa
Create Date: 2026-04-17 17:40:14.742500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78508fc70a67'
down_revision = '1901cef5ccfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deletion_mark', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Technical Task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Technical Task',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('deletion_mark', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Technical Task_pkey'))
    )
    op.drop_table('technical_task')
    # ### end Alembic commands ###
