"""empty message

Revision ID: 7c46ea2e47ab
Revises: 8e50e9b16407
Create Date: 2026-06-22 12:03:56.401706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c46ea2e47ab'
down_revision = '8e50e9b16407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_info', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
