"""empty message

Revision ID: 8e50e9b16407
Revises: 05eb9a50ddec
Create Date: 2026-06-19 15:29:34.191904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e50e9b16407'
down_revision = '05eb9a50ddec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
