"""empty message

Revision ID: 9d4c507323c5
Revises: ae7916b04fdb
Create Date: 2026-07-06 18:36:25.428092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4c507323c5'
down_revision = 'ae7916b04fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('technical_task_organization_ref_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('technical_task_efo_ref_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('technical_task_efo_ref_fkey'), 'equipment', ['efo_ref'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('technical_task_organization_ref_fkey'), 'organization', ['organization_ref'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
