"""empty message

Revision ID: aa9d32443a19
Revises: 5501b4e6e676
Create Date: 2026-07-03 17:45:30.565366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa9d32443a19'
down_revision = '5501b4e6e676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_ref', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('efo_ref', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('combat_impact', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('malfunction_time', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('measurement_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('creation_date', sa.Date(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('technical_task_organization_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('technical_task_efo_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organization', ['organization_ref'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'equipment', ['efo_ref'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('bg_impact')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('fault_detected_at')
        batch_op.drop_column('monitoring_id')
        batch_op.drop_column('efo_id')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('efo_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('monitoring_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fault_detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bg_impact', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('technical_task_efo_id_fkey'), 'equipment', ['efo_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('technical_task_organization_id_fkey'), 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('creation_date')
        batch_op.drop_column('measurement_id')
        batch_op.drop_column('malfunction_time')
        batch_op.drop_column('combat_impact')
        batch_op.drop_column('efo_ref')
        batch_op.drop_column('organization_ref')

    # ### end Alembic commands ###
