"""empty message

Revision ID: afe2936a32f8
Revises: 
Create Date: 2026-07-13 18:35:06.684443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe2936a32f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('equipment_name', sa.String(length=255), nullable=False),
    sa.Column('from_designation', sa.String(length=255), nullable=True),
    sa.Column('factory_number', sa.String(length=255), nullable=True),
    sa.Column('esi_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('org_type', sa.String(length=255), nullable=True),
    sa.Column('org_title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('creating_author_id', sa.UUID(), nullable=True),
    sa.Column('deleting_author_id', sa.UUID(), nullable=True),
    sa.Column('organization_ref', sa.UUID(), nullable=True),
    sa.Column('efo_ref', sa.UUID(), nullable=True),
    sa.Column('combat_impact', sa.Boolean(), nullable=True),
    sa.Column('malfunction_time', sa.DateTime(), nullable=True),
    sa.Column('measurement_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deletion_mark', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['creating_author_id'], ['person_info.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleting_author_id'], ['person_info.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['efo_ref'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_ref'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['technical_task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person_info.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['technical_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_person')
    op.drop_table('technical_task')
    op.drop_table('person_info')
    op.drop_table('organization')
    op.drop_table('equipment')
    # ### end Alembic commands ###
