"""change measurement_id from UUID to Integer

Revision ID: b13ce421dbfd
Revises: afe2936a32f8
Create Date: 2026-07-13 18:48:32.361812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13ce421dbfd'
down_revision = 'afe2936a32f8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.drop_column('measurement_id')

    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('measurement_id', sa.Integer(), nullable=True)
        )


def downgrade():
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.drop_column('measurement_id')

    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('measurement_id', sa.UUID(), nullable=True)
        )


"""empty message

Revision ID: b13ce421dbfd
Revises: afe2936a32f8
Create Date: 2026-07-13 18:48:32.361812


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13ce421dbfd'
down_revision = 'afe2936a32f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.alter_column('measurement_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.alter_column('measurement_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)

    # ### end Alembic commands ###
"""
