"""empty message

Revision ID: c4076a542dae
Revises: 49554bbaae23
Create Date: 2026-09-23 18:12:43.816045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4076a542dae'
down_revision = '49554bbaae23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_designation', sa.String(length=255), nullable=True))
        batch_op.drop_column('from_designation')

    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tz_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.drop_column('tz_date')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_designation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('form_designation')

    # ### end Alembic commands ###
