"""empty message

Revision ID: c4f76aa8a395
Revises: 9d4c507323c5
Create Date: 2026-07-07 15:01:46.303846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f76aa8a395'
down_revision = '9d4c507323c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_info', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('person_info_organization_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_info', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('person_info_organization_id_fkey'), 'organization', ['organization_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
