"""empty message

Revision ID: cfa572c2edab
Revises: 78508fc70a67
Create Date: 2026-04-17 19:02:50.496327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa572c2edab'
down_revision = '78508fc70a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('creating_author_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('creating_author_id')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
