"""empty message

Revision ID: d6d0f5ec582d
Revises: dda76e45a0ac
Create Date: 2026-08-07 12:04:14.998846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d0f5ec582d'
down_revision = 'dda76e45a0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_info', schema=None) as batch_op:
        batch_op.drop_column('is_multiple')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_multiple', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
