"""empty message

Revision ID: da1b6194bd2c
Revises: 07c334c3f9bc
Create Date: 2026-07-16 17:12:50.750671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1b6194bd2c'
down_revision = '07c334c3f9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_info', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_technical_task_measurement_id', ['measurement_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_task', schema=None) as batch_op:
        batch_op.drop_constraint('uq_technical_task_measurement_id', type_='unique')

    with op.batch_alter_table('role_info', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
