"""empty message

Revision ID: dda76e45a0ac
Revises: da1b6194bd2c
Create Date: 2026-08-06 11:45:38.985295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda76e45a0ac'
down_revision = 'da1b6194bd2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_multiple', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_info', schema=None) as batch_op:
        batch_op.drop_column('is_multiple')

    # ### end Alembic commands ###
